{
 "title": "Kubescape",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Compliance Score by framework",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubescape_framework_complianceScore) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Control Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (kubescape_control_complianceScore) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overtime Cluster Risk score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kubescape_cluster_complianceScore"
    }
   ]
  },
  {
   "title": "Overtime Controls Risk score ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kubescape_control_complianceScore) by (name)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "Overtime Frameworks Risk score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kubescape_framework_complianceScore) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by Status",
   "type": "piechart",
   "description": "Number of Resources that failed/passed or skipped",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubescape_control_count_resources_passed)",
     "legendFormat": "passed"
    },
    {
     "expr": "sum(kubescape_control_count_resources_failed)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kubescape_control_count_resources_skipped)",
     "legendFormat": "skipped"
    }
   ]
  },
  {
   "title": "Controls by Status",
   "type": "piechart",
   "description": "Number of controls that failed/passed or skipped\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_cluster_count_control_failed",
     "legendFormat": "failed"
    },
    {
     "expr": "kubescape_cluster_count_control_skipped",
     "legendFormat": "skipped"
    },
    {
     "expr": "kubescape_cluster_count_control_passed",
     "legendFormat": "passed"
    }
   ]
  }
 ]
}