apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store-dev
  labels:
    argocd.argoproj.io/instance: external-secrets-infra
spec:
  provider:
    azurekv:
      tenantId: 8052b405-12c9-4ba1-a5b3-117899e42975 #TODO: Change this
      vaultUrl: https://mysecretskv.vault.azure.net #TODO: Change this
      authType: ServicePrincipal
      environmentType: PublicCloud
      authSecretRef:
        clientId:
          name: azure-creds
          key: client-id
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: client-secret
          namespace: external-secrets 
    

