---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: app1
    repoURL: https://github.com/aminrj/10-gitops.git
    targetRevision: HEAD
  project: default

