---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: dev
    repoURL: https://github.com/aminrj/10-gitops.git
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc

