apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
spec:
  generators:
    - git:
        repoURL: https://github.com/aminrj/devops-labs.git
        revision: ha-posgtgres-cnpg
        directories:
          - path: "80-cnpg/databases/*/overlays/*"
  template:
    metadata:
      name: "{{path.basename}}-db"
    spec:
      project: default
      source:
        repoURL: https://github.com/aminrj/devops-labs.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: cnpg-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
