apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-dev
    kind: ClusterSecretStore
  target:
    name: n8n-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: n8n-db-username
    - secretKey: password
      remoteRef:
        key: n8n-db-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-encryption
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-dev
    kind: ClusterSecretStore
  target:
    name: n8n-encryption
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: n8n-encryption-key
