apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app1
            namespace: app1-ns
          - name: app2
            namespace: app2-ns
  template:
    metadata:
      name: '{{name}}'
      namespace: '{{namespace}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/aminrj/10-gitops.git
        targetRevision: HEAD
        path: dev/apps/{{name}}
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true